name: 'my deneme'

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - development
jobs:
  dummy_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Do nothing
        run: echo > /dev/null
 